## Assignment

Is assignment mein aapko multiple Machine Learning classification models use karne hain including:

• *Logistic Regression*
• *Decision Tree*
• *SVC*
• *KNN*

Requirements:

1. Sab models ki proper pipeline banani hai
2. Sara kaam aik hi `.ipynb` file mein hona chahiye
3. Har model ki accuracy compare karni hai
4. Jis model ki accuracy sab se best ho us model ko save karna hai as `model.pkl`
5. Us saved model ki FastAPI mein API banani hai
6. Streamlit frontend create karna hai
7. Project deploy karna hai aur working demo link share karna hai

### 1. Work on Logistic Regression:

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  StandardScaler

In [3]:
data = pd.read_csv('adult.csv')
data.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [41]:
data.duplicated().sum()

np.int64(52)

In [9]:
data.workclass.unique()

array(['Private', 'Local-gov', '?', 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [11]:
data.income.unique()

array(['<=50K', '>50K'], dtype=object)

In [12]:
X = data.drop("income", axis=1)
y = data.income

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [26]:
cat_cols = X_train.select_dtypes('object')
num_cols = X_train.select_dtypes('number')

In [27]:
cat_cols

,workclass,education,marital-status,occupation,relationship,race,gender,native-country
37193,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States
31093,Self-emp-not-inc,10th,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States
33814,Local-gov,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States
14500,Private,HS-grad,Never-married,Adm-clerical,Not-in-family,White,Female,United-States
23399,Private,Assoc-voc,Never-married,Transport-moving,Not-in-family,White,Male,United-States
...,...,...,...,...,...,...,...,...
11284,Private,HS-grad,Married-spouse-absent,Other-service,Not-in-family,Black,Male,United-States
44732,Private,Some-college,Married-civ-spouse,Craft-repair,Husband,White,Male,United-States
38158,Private,Some-college,Divorced,Exec-managerial,Not-in-family,White,Female,United-States
860,State-gov,Assoc-voc,Separated,Adm-clerical,Unmarried,Black,Female,United-States
15795,Private,Masters,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States

In [28]:
num_cols

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
37193,42,145175,10,0,0,40
31093,52,175029,6,0,0,35
33814,34,172664,9,0,0,40
14500,28,125791,9,0,0,40
23399,46,28419,11,0,0,50
...,...,...,...,...,...,...
11284,36,635913,9,0,0,40
44732,34,107624,10,0,0,50
38158,28,250135,10,0,0,40
860,46,96652,11,0,0,40
15795,59,176118,14,0,0,7

In [29]:
model  = LogisticRegression()

In [30]:
#  Numerical pipeline
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),   # handle missing numbers
    ("scaler", StandardScaler())
])

# Categorical pipeline
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),  # handle missing categories
    ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore",sparse_output=False))
])

In [31]:
preprocessor = ColumnTransformer(
                            transformers=[
                            ("num", num_pipeline, num_cols.columns),
                            ("cat", cat_pipeline, cat_cols.columns)
                            ])

In [32]:
model_pipeline = Pipeline(
    [
    ("preprocessor",  preprocessor),
    ("model", model)
    ]
)

model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss',
       'hours-per-week'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'gender', 'native-country'],
      dtype='object'))])),
                ('model', LogisticRegression())])

In [33]:
(num_cols - num_cols.min()) / (num_cols.max()-num_cols.min())

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
37193,0.342466,0.090253,0.600000,0.0,0.0,0.397959
31093,0.479452,0.110528,0.333333,0.0,0.0,0.346939
33814,0.232877,0.108922,0.533333,0.0,0.0,0.397959
14500,0.150685,0.077088,0.533333,0.0,0.0,0.397959
23399,0.397260,0.010957,0.666667,0.0,0.0,0.500000
...,...,...,...,...,...,...
11284,0.260274,0.423539,0.533333,0.0,0.0,0.397959
44732,0.232877,0.064750,0.600000,0.0,0.0,0.500000
38158,0.150685,0.161537,0.600000,0.0,0.0,0.397959
860,0.397260,0.057298,0.666667,0.0,0.0,0.397959
15795,0.575342,0.111268,0.866667,0.0,0.0,0.061224

In [36]:
((num_cols - num_cols.mean()) / num_cols.std())['educational-num'].mean()

np.float64(-2.4295167890243744e-16)

In [37]:
((num_cols - num_cols.mean()) / num_cols.std())['educational-num'].std()

1.0000000000003006